name: Node.js CI publish

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Build and lint with ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build:ext
      - run: npm run lint

      - name: Get version from package.json
        id: get_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "Version is $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Upload the release
        id: upload-release-asset
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: web-ext-artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.version }}" # Use the version as tag
          release_name: "Release v${{ env.version }}"
          draft: false
          prerelease: false

      - name: Upload ZIP to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/*.zip # Path to your .zip file
          asset_name: rss_launchpad_find_feeds_easily-${{ env.version }}.zip # Name with version
          asset_content_type: application/zip
